update tournament_participant set number_of_victories = 6 where team_name = 'Duke' and year = 2010;
update tournament_participant set number_of_victories = 5 where team_name = 'Butler' and year =  2010;
update tournament_participant set number_of_victories = 4 where team_name = 'Michigan St' and year =  2010;
update tournament_participant set number_of_victories = 4 where team_name = 'West Virginia' and year =  2010;
update tournament_participant set number_of_victories = 3 where team_name = 'Baylor' and year = 2010;
update tournament_participant set number_of_victories = 3 where team_name = 'Kentucky'            and year = 2010;
update tournament_participant set number_of_victories = 3 where team_name = 'Tennessee'           and year = 2010;
update tournament_participant set number_of_victories = 3 where team_name = 'Kansas St'           and year = 2010;
update tournament_participant set number_of_victories = 2 where team_name = 'Purdue'              and year = 2010;
update tournament_participant set number_of_victories = 2 where team_name = 'Washington'          and year = 2010;
update tournament_participant set number_of_victories = 2 where team_name = 'Xavier'              and year = 2010;
update tournament_participant set number_of_victories = 2 where team_name = 'Ohio St'             and year = 2010;
update tournament_participant set number_of_victories = 2 where team_name = 'Cornell'             and year = 2010;
update tournament_participant set number_of_victories = 2 where team_name = 'Syracuse'            and year = 2010;
update tournament_participant set number_of_victories = 2 where team_name = 'Saint Marys CA'      and year = 2010;
update tournament_participant set number_of_victories = 2 where team_name = 'UNI'                 and year = 2010;
update tournament_participant set number_of_victories = 1 where team_name = 'Ohio'                and year = 2010;
update tournament_participant set number_of_victories = 1 where team_name = 'Texas AM'            and year = 2010;
update tournament_participant set number_of_victories = 1 where team_name = 'Wake Forest'         and year = 2010;
update tournament_participant set number_of_victories = 1 where team_name = 'Ark-Pine Bluff'      and year = 2010;
update tournament_participant set number_of_victories = 1 where team_name = 'Missouri'            and year = 2010;
update tournament_participant set number_of_victories = 1 where team_name = 'Old Dominion'        and year = 2010;
update tournament_participant set number_of_victories = 1 where team_name = 'New Mexico'          and year = 2010;
update tournament_participant set number_of_victories = 1 where team_name = 'Kansas'              and year = 2010;
update tournament_participant set number_of_victories = 1 where team_name = 'Pittsburgh'          and year = 2010;
update tournament_participant set number_of_victories = 1 where team_name = 'Murray St'           and year = 2010;
update tournament_participant set number_of_victories = 1 where team_name = 'Villanova'           and year = 2010;
update tournament_participant set number_of_victories = 1 where team_name = 'California'          and year = 2010;
update tournament_participant set number_of_victories = 1 where team_name = 'Gonzaga'             and year = 2010;
update tournament_participant set number_of_victories = 1 where team_name = 'Georgia Tech'        and year = 2010;
update tournament_participant set number_of_victories = 1 where team_name = 'Maryland'            and year = 2010;
update tournament_participant set number_of_victories = 1 where team_name = 'Wisconsin'           and year = 2010;
update tournament_participant set number_of_victories = 1 where team_name = 'BYU' and year = 2010;
update tournament_participant set number_of_victories = 6 where team_name = 'UConn'               and year = 2011;
update tournament_participant set number_of_victories = 5 where team_name = 'Butler'              and year = 2011;
update tournament_participant set number_of_victories = 5 where team_name = 'VCU'                 and year = 2011;
update tournament_participant set number_of_victories = 4 where team_name = 'Kentucky'            and year = 2011;
update tournament_participant set number_of_victories = 3 where team_name = 'Arizona'             and year = 2011;
update tournament_participant set number_of_victories = 3 where team_name = 'Florida'             and year = 2011;
update tournament_participant set number_of_victories = 3 where team_name = 'North Carolina'      and year = 2011;
update tournament_participant set number_of_victories = 3 where team_name = 'Kansas'              and year = 2011;
update tournament_participant set number_of_victories = 2 where team_name = 'Richmond'            and year = 2011;
update tournament_participant set number_of_victories = 2 where team_name = 'San Diego St'        and year = 2011;
update tournament_participant set number_of_victories = 2 where team_name = 'Duke'                and year = 2011;
update tournament_participant set number_of_victories = 2 where team_name = 'Marquette'           and year = 2011;
update tournament_participant set number_of_victories = 2 where team_name = 'Wisconsin'           and year = 2011;
update tournament_participant set number_of_victories = 2 where team_name = 'Ohio St'             and year = 2011;
update tournament_participant set number_of_victories = 2 where team_name = 'Florida St'          and year = 2011;
update tournament_participant set number_of_victories = 2 where team_name = 'BYU'                 and year = 2011;
update tournament_participant set number_of_victories = 1 where team_name = 'Washington'          and year = 2011;
update tournament_participant set number_of_victories = 1 where team_name = 'West Virginia'       and year = 2011;
update tournament_participant set number_of_victories = 1 where team_name = 'Texas'               and year = 2011;
update tournament_participant set number_of_victories = 1 where team_name = 'Illinois'            and year = 2011;
update tournament_participant set number_of_victories = 1 where team_name = 'Gonzaga'             and year = 2011;
update tournament_participant set number_of_victories = 1 where team_name = 'Clemson'             and year = 2011;
update tournament_participant set number_of_victories = 1 where team_name = 'Temple'              and year = 2011;
update tournament_participant set number_of_victories = 1 where team_name = 'Cincinnati'          and year = 2011;
update tournament_participant set number_of_victories = 1 where team_name = 'UNC Asheville'       and year = 2011;
update tournament_participant set number_of_victories = 1 where team_name = 'Pittsburgh'          and year = 2011;
update tournament_participant set number_of_victories = 1 where team_name = 'UTSA'                and year = 2011;
update tournament_participant set number_of_victories = 1 where team_name = 'Purdue'              and year = 2011;
update tournament_participant set number_of_victories = 1 where team_name = 'UCLA'                and year = 2011;
update tournament_participant set number_of_victories = 1 where team_name = 'Morehead St'         and year = 2011;
update tournament_participant set number_of_victories = 1 where team_name = 'Kansas St'           and year = 2011;
update tournament_participant set number_of_victories = 1 where team_name = 'Michigan'            and year = 2011;
update tournament_participant set number_of_victories = 1 where team_name = 'Syracuse'            and year = 2011;
update tournament_participant set number_of_victories = 1 where team_name = 'George Mason'        and year = 2011;
update tournament_participant set number_of_victories = 1 where team_name = 'Notre Dame'          and year = 2011;
update tournament_participant set number_of_victories = 6 where team_name = 'Kentucky'            and year = 2012;
update tournament_participant set number_of_victories = 5 where team_name = 'Kansas'              and year = 2012;
update tournament_participant set number_of_victories = 4 where team_name = 'Louisville'          and year = 2012;
update tournament_participant set number_of_victories = 4 where team_name = 'Ohio St'             and year = 2012;
update tournament_participant set number_of_victories = 3 where team_name = 'Baylor'              and year = 2012;
update tournament_participant set number_of_victories = 3 where team_name = 'Florida'             and year = 2012;
update tournament_participant set number_of_victories = 3 where team_name = 'Syracuse'            and year = 2012;
update tournament_participant set number_of_victories = 3 where team_name = 'North Carolina'      and year = 2012;
update tournament_participant set number_of_victories = 2 where team_name = 'Xavier'              and year = 2012;
update tournament_participant set number_of_victories = 2 where team_name = 'Indiana'             and year = 2012;
update tournament_participant set number_of_victories = 2 where team_name = 'Cincinnati'          and year = 2012;
update tournament_participant set number_of_victories = 2 where team_name = 'Wisconsin'           and year = 2012;
update tournament_participant set number_of_victories = 2 where team_name = 'NC State'            and year = 2012;
update tournament_participant set number_of_victories = 2 where team_name = 'Ohio'                and year = 2012;
update tournament_participant set number_of_victories = 2 where team_name = 'South Fla'           and year = 2012;
update tournament_participant set number_of_victories = 2 where team_name = 'Michigan St'         and year = 2012;
update tournament_participant set number_of_victories = 2 where team_name = 'Marquette'           and year = 2012;
update tournament_participant set number_of_victories = 1 where team_name = 'Florida St'          and year = 2012;
update tournament_participant set number_of_victories = 1 where team_name = 'Creighton'           and year = 2012;
update tournament_participant set number_of_victories = 1 where team_name = 'Kansas St'           and year = 2012;
update tournament_participant set number_of_victories = 1 where team_name = 'Murray St'           and year = 2012;
update tournament_participant set number_of_victories = 1 where team_name = 'Iowa St'             and year = 2012;
update tournament_participant set number_of_victories = 1 where team_name = 'BYU'                 and year = 2012;
update tournament_participant set number_of_victories = 1 where team_name = 'Purdue'              and year = 2012;
update tournament_participant set number_of_victories = 1 where team_name = 'Norfolk St'          and year = 2012;
update tournament_participant set number_of_victories = 1 where team_name = 'Lehigh'              and year = 2012;
update tournament_participant set number_of_victories = 1 where team_name = 'Vanderbilt'          and year = 2012;
update tournament_participant set number_of_victories = 1 where team_name = 'Saint Louis'         and year = 2012;
update tournament_participant set number_of_victories = 1 where team_name = 'Colorado'            and year = 2012;
update tournament_participant set number_of_victories = 1 where team_name = 'Vermont'             and year = 2012;
update tournament_participant set number_of_victories = 1 where team_name = 'VCU'                 and year = 2012;
update tournament_participant set number_of_victories = 1 where team_name = 'Western Ky'          and year = 2012;
update tournament_participant set number_of_victories = 1 where team_name = 'Georgetown'          and year = 2012;
update tournament_participant set number_of_victories = 1 where team_name = 'Gonzaga'             and year = 2012;
update tournament_participant set number_of_victories = 1 where team_name = 'New Mexico'          and year = 2012;
update tournament_participant set number_of_victories = 6 where team_name = 'Louisville'          and year = 2013;
update tournament_participant set number_of_victories = 5 where team_name = 'Michigan'            and year = 2013;
update tournament_participant set number_of_victories = 4 where team_name = 'Syracuse'            and year = 2013;
update tournament_participant set number_of_victories = 4 where team_name = 'Wichita St'          and year = 2013;
update tournament_participant set number_of_victories = 3 where team_name = 'Ohio St'             and year = 2013;
update tournament_participant set number_of_victories = 3 where team_name = 'Marquette'           and year = 2013;
update tournament_participant set number_of_victories = 3 where team_name = 'Duke'                and year = 2013;
update tournament_participant set number_of_victories = 3 where team_name = 'La Salle'            and year = 2013;
update tournament_participant set number_of_victories = 3 where team_name = 'Florida'             and year = 2013;
update tournament_participant set number_of_victories = 2 where team_name = 'Indiana'             and year = 2013;
update tournament_participant set number_of_victories = 2 where team_name = 'Arizona'             and year = 2013;
update tournament_participant set number_of_victories = 2 where team_name = 'Oregon'              and year = 2013;
update tournament_participant set number_of_victories = 2 where team_name = 'Miami FL'            and year = 2013;
update tournament_participant set number_of_victories = 2 where team_name = 'Michigan St'         and year = 2013;
update tournament_participant set number_of_victories = 2 where team_name = 'FGCU'                and year = 2013;
update tournament_participant set number_of_victories = 2 where team_name = 'Kansas'              and year = 2013;
update tournament_participant set number_of_victories = 1 where team_name = 'Iowa St'             and year = 2013;
update tournament_participant set number_of_victories = 1 where team_name = 'Saint Marys CA'      and year = 2013;
update tournament_participant set number_of_victories = 1 where team_name = 'Illinois'            and year = 2013;
update tournament_participant set number_of_victories = 1 where team_name = 'Minnesota'           and year = 2013;
update tournament_participant set number_of_victories = 1 where team_name = 'Colorado St'         and year = 2013;
update tournament_participant set number_of_victories = 1 where team_name = 'Harvard'             and year = 2013;
update tournament_participant set number_of_victories = 1 where team_name = 'North Carolina'      and year = 2013;
update tournament_participant set number_of_victories = 1 where team_name = 'Butler'              and year = 2013;
update tournament_participant set number_of_victories = 1 where team_name = 'Memphis'             and year = 2013;
update tournament_participant set number_of_victories = 1 where team_name = 'Gonzaga'             and year = 2013;
update tournament_participant set number_of_victories = 1 where team_name = 'NC AT'               and year = 2013;
update tournament_participant set number_of_victories = 1 where team_name = 'San Diego St'        and year = 2013;
update tournament_participant set number_of_victories = 1 where team_name = 'VCU'                 and year = 2013;
update tournament_participant set number_of_victories = 1 where team_name = 'Ole Miss'            and year = 2013;
update tournament_participant set number_of_victories = 1 where team_name = 'James Madison'       and year = 2013;
update tournament_participant set number_of_victories = 1 where team_name = 'Creighton'           and year = 2013;
update tournament_participant set number_of_victories = 1 where team_name = 'Temple'              and year = 2013;
update tournament_participant set number_of_victories = 1 where team_name = 'Saint Louis'         and year = 2013;
update tournament_participant set number_of_victories = 1 where team_name = 'California'          and year = 2013;
update tournament_participant set number_of_victories = 6 where team_name = 'UConn'               and year = 2014;
update tournament_participant set number_of_victories = 5 where team_name = 'Kentucky'            and year = 2014;
update tournament_participant set number_of_victories = 4 where team_name = 'Wisconsin'           and year = 2014;
update tournament_participant set number_of_victories = 4 where team_name = 'Florida'             and year = 2014;
update tournament_participant set number_of_victories = 3 where team_name = 'Tennessee'           and year = 2014;
update tournament_participant set number_of_victories = 3 where team_name = 'Michigan'            and year = 2014;
update tournament_participant set number_of_victories = 3 where team_name = 'Arizona'             and year = 2014;
update tournament_participant set number_of_victories = 3 where team_name = 'Dayton'              and year = 2014;
update tournament_participant set number_of_victories = 3 where team_name = 'Michigan St'         and year = 2014;
update tournament_participant set number_of_victories = 2 where team_name = 'UCLA'                and year = 2014;
update tournament_participant set number_of_victories = 2 where team_name = 'Iowa St'             and year = 2014;
update tournament_participant set number_of_victories = 2 where team_name = 'Baylor'              and year = 2014;
update tournament_participant set number_of_victories = 2 where team_name = 'Virginia'            and year = 2014;
update tournament_participant set number_of_victories = 2 where team_name = 'Louisville'          and year = 2014;
update tournament_participant set number_of_victories = 2 where team_name = 'Stanford'            and year = 2014;
update tournament_participant set number_of_victories = 2 where team_name = 'San Diego St'        and year = 2014;
update tournament_participant set number_of_victories = 1 where team_name = 'Mercer'              and year = 2014;
update tournament_participant set number_of_victories = 1 where team_name = 'Harvard'             and year = 2014;
update tournament_participant set number_of_victories = 1 where team_name = 'Cal Poly'            and year = 2014;
update tournament_participant set number_of_victories = 1 where team_name = 'Kansas'              and year = 2014;
update tournament_participant set number_of_victories = 1 where team_name = 'SFA'                 and year = 2014;
update tournament_participant set number_of_victories = 1 where team_name = 'Syracuse'            and year = 2014;
update tournament_participant set number_of_victories = 1 where team_name = 'Texas'               and year = 2014;
update tournament_participant set number_of_victories = 1 where team_name = 'Oregon'              and year = 2014;
update tournament_participant set number_of_victories = 1 where team_name = 'NC State'            and year = 2014;
update tournament_participant set number_of_victories = 1 where team_name = 'Albany NY'           and year = 2014;
update tournament_participant set number_of_victories = 1 where team_name = 'Pittsburgh'          and year = 2014;
update tournament_participant set number_of_victories = 1 where team_name = 'Memphis'             and year = 2014;
update tournament_participant set number_of_victories = 1 where team_name = 'Gonzaga'             and year = 2014;
update tournament_participant set number_of_victories = 1 where team_name = 'North Dakota St'     and year = 2014;
update tournament_participant set number_of_victories = 1 where team_name = 'Saint Louis'         and year = 2014;
update tournament_participant set number_of_victories = 1 where team_name = 'Villanova'           and year = 2014;
update tournament_participant set number_of_victories = 1 where team_name = 'North Carolina'      and year = 2014;
update tournament_participant set number_of_victories = 1 where team_name = 'Wichita St'          and year = 2014;
update tournament_participant set number_of_victories = 1 where team_name = 'Creighton'           and year = 2014;
update tournament_participant set number_of_victories = 6 where team_name = 'Duke'                and year = 2015;
update tournament_participant set number_of_victories = 5 where team_name = 'Wisconsin'           and year = 2015;
update tournament_participant set number_of_victories = 4 where team_name = 'Michigan St'         and year = 2015;
update tournament_participant set number_of_victories = 4 where team_name = 'Kentucky'            and year = 2015;
update tournament_participant set number_of_victories = 3 where team_name = 'Louisville'          and year = 2015;
update tournament_participant set number_of_victories = 3 where team_name = 'Notre Dame'          and year = 2015;
update tournament_participant set number_of_victories = 3 where team_name = 'Arizona'             and year = 2015;
update tournament_participant set number_of_victories = 3 where team_name = 'Gonzaga'             and year = 2015;
update tournament_participant set number_of_victories = 2 where team_name = 'UCLA'                and year = 2015;
update tournament_participant set number_of_victories = 2 where team_name = 'West Virginia'       and year = 2015;
update tournament_participant set number_of_victories = 2 where team_name = 'North Carolina'      and year = 2015;
update tournament_participant set number_of_victories = 2 where team_name = 'Dayton'              and year = 2015;
update tournament_participant set number_of_victories = 2 where team_name = 'Oklahoma'            and year = 2015;
update tournament_participant set number_of_victories = 2 where team_name = 'Wichita St'          and year = 2015;
update tournament_participant set number_of_victories = 2 where team_name = 'NC State'            and year = 2015;
update tournament_participant set number_of_victories = 2 where team_name = 'Xavier'              and year = 2015;
update tournament_participant set number_of_victories = 2 where team_name = 'Utah'                and year = 2015;
update tournament_participant set number_of_victories = 1 where team_name = 'Georgia St'          and year = 2015;
update tournament_participant set number_of_victories = 1 where team_name = 'Arkansas'            and year = 2015;
update tournament_participant set number_of_victories = 1 where team_name = 'Villanova'           and year = 2015;
update tournament_participant set number_of_victories = 1 where team_name = 'Maryland'            and year = 2015;
update tournament_participant set number_of_victories = 1 where team_name = 'Kansas'              and year = 2015;
update tournament_participant set number_of_victories = 1 where team_name = 'UAB'                 and year = 2015;
update tournament_participant set number_of_victories = 1 where team_name = 'Iowa'                and year = 2015;
update tournament_participant set number_of_victories = 1 where team_name = 'Virginia'            and year = 2015;
update tournament_participant set number_of_victories = 1 where team_name = 'Oregon'              and year = 2015;
update tournament_participant set number_of_victories = 1 where team_name = 'UNI'                 and year = 2015;
update tournament_participant set number_of_victories = 1 where team_name = 'San Diego St'        and year = 2015;
update tournament_participant set number_of_victories = 1 where team_name = 'Ole Miss'            and year = 2015;
update tournament_participant set number_of_victories = 1 where team_name = 'Butler'              and year = 2015;
update tournament_participant set number_of_victories = 1 where team_name = 'Robert Morris'       and year = 2015;
update tournament_participant set number_of_victories = 1 where team_name = 'Hampton'             and year = 2015;
update tournament_participant set number_of_victories = 1 where team_name = 'Georgetown'          and year = 2015;
update tournament_participant set number_of_victories = 1 where team_name = 'Cincinnati'          and year = 2015;
update tournament_participant set number_of_victories = 1 where team_name = 'Ohio St'             and year = 2015;
update tournament_participant set number_of_victories = 6 where team_name = 'Villanova'           and year = 2016;
update tournament_participant set number_of_victories = 5 where team_name = 'North Carolina'      and year = 2016;
update tournament_participant set number_of_victories = 4 where team_name = 'Oklahoma'            and year = 2016;
update tournament_participant set number_of_victories = 4 where team_name = 'Syracuse'            and year = 2016;
update tournament_participant set number_of_victories = 3 where team_name = 'Kansas'              and year = 2016;
update tournament_participant set number_of_victories = 3 where team_name = 'Virginia'            and year = 2016;
update tournament_participant set number_of_victories = 3 where team_name = 'Notre Dame'          and year = 2016;
update tournament_participant set number_of_victories = 3 where team_name = 'Oregon'              and year = 2016;
update tournament_participant set number_of_victories = 2 where team_name = 'Maryland'            and year = 2016;
update tournament_participant set number_of_victories = 2 where team_name = 'Miami FL'            and year = 2016;
update tournament_participant set number_of_victories = 2 where team_name = 'Texas AM'            and year = 2016;
update tournament_participant set number_of_victories = 2 where team_name = 'Wichita St'          and year = 2016;
update tournament_participant set number_of_victories = 2 where team_name = 'Iowa St'             and year = 2016;
update tournament_participant set number_of_victories = 2 where team_name = 'Indiana'             and year = 2016;
update tournament_participant set number_of_victories = 2 where team_name = 'Gonzaga'             and year = 2016;
update tournament_participant set number_of_victories = 2 where team_name = 'Duke'                and year = 2016;
update tournament_participant set number_of_victories = 2 where team_name = 'Wisconsin'           and year = 2016;
update tournament_participant set number_of_victories = 1 where team_name = 'Michigan'            and year = 2016;
update tournament_participant set number_of_victories = 1 where team_name = 'Saint Josephs'       and year = 2016;
update tournament_participant set number_of_victories = 1 where team_name = 'Providence'          and year = 2016;
update tournament_participant set number_of_victories = 1 where team_name = 'Kentucky'            and year = 2016;
update tournament_participant set number_of_victories = 1 where team_name = 'Utah'                and year = 2016;
update tournament_participant set number_of_victories = 1 where team_name = 'FGCU'                and year = 2016;
update tournament_participant set number_of_victories = 1 where team_name = 'Middle Tenn'         and year = 2016;
update tournament_participant set number_of_victories = 1 where team_name = 'UNI'                 and year = 2016;
update tournament_participant set number_of_victories = 1 where team_name = 'Iowa'                and year = 2016;
update tournament_participant set number_of_victories = 1 where team_name = 'Butler'              and year = 2016;
update tournament_participant set number_of_victories = 1 where team_name = 'Xavier'              and year = 2016;
update tournament_participant set number_of_victories = 1 where team_name = 'UConn'               and year = 2016;
update tournament_participant set number_of_victories = 1 where team_name = 'Yale'                and year = 2016;
update tournament_participant set number_of_victories = 1 where team_name = 'VCU'                 and year = 2016;
update tournament_participant set number_of_victories = 1 where team_name = 'Little Rock'         and year = 2016;
update tournament_participant set number_of_victories = 1 where team_name = 'SFA'                 and year = 2016;
update tournament_participant set number_of_victories = 1 where team_name = 'Hawaii'              and year = 2016;
update tournament_participant set number_of_victories = 1 where team_name = 'Holy Cross'          and year = 2016;
update tournament_participant set number_of_victories = 6 where team_name = 'North Carolina'      and year = 2017;
update tournament_participant set number_of_victories = 5 where team_name = 'Gonzaga'             and year = 2017;
update tournament_participant set number_of_victories = 4 where team_name = 'South Carolina'      and year = 2017;
update tournament_participant set number_of_victories = 4 where team_name = 'Oregon'              and year = 2017;
update tournament_participant set number_of_victories = 3 where team_name = 'Florida'             and year = 2017;
update tournament_participant set number_of_victories = 3 where team_name = 'Kentucky'            and year = 2017;
update tournament_participant set number_of_victories = 3 where team_name = 'Xavier'              and year = 2017;
update tournament_participant set number_of_victories = 3 where team_name = 'Kansas'              and year = 2017;
update tournament_participant set number_of_victories = 2 where team_name = 'Wisconsin'           and year = 2017;
update tournament_participant set number_of_victories = 2 where team_name = 'UCLA'                and year = 2017;
update tournament_participant set number_of_victories = 2 where team_name = 'Michigan'            and year = 2017;
update tournament_participant set number_of_victories = 2 where team_name = 'Southern California' and year = 2017;
update tournament_participant set number_of_victories = 2 where team_name = 'West Virginia'       and year = 2017;
update tournament_participant set number_of_victories = 2 where team_name = 'Arizona'             and year = 2017;
update tournament_participant set number_of_victories = 2 where team_name = 'Purdue'              and year = 2017;
update tournament_participant set number_of_victories = 2 where team_name = 'Butler'              and year = 2017;
update tournament_participant set number_of_victories = 2 where team_name = 'Baylor'              and year = 2017;
update tournament_participant set number_of_victories = 1 where team_name = 'UC Davis'            and year = 2017;
update tournament_participant set number_of_victories = 1 where team_name = 'Notre Dame'          and year = 2017;
update tournament_participant set number_of_victories = 1 where team_name = 'Florida St'          and year = 2017;
update tournament_participant set number_of_victories = 1 where team_name = 'Rhode Island'        and year = 2017;
update tournament_participant set number_of_victories = 1 where team_name = 'Mt St Marys'         and year = 2017;
update tournament_participant set number_of_victories = 1 where team_name = 'Duke'                and year = 2017;
update tournament_participant set number_of_victories = 1 where team_name = 'Northwestern'        and year = 2017;
update tournament_participant set number_of_victories = 1 where team_name = 'Louisville'          and year = 2017;
update tournament_participant set number_of_victories = 1 where team_name = 'Middle Tenn'         and year = 2017;
update tournament_participant set number_of_victories = 1 where team_name = 'Iowa St'             and year = 2017;
update tournament_participant set number_of_victories = 1 where team_name = 'Wichita St'          and year = 2017;
update tournament_participant set number_of_victories = 1 where team_name = 'Kansas St'           and year = 2017;
update tournament_participant set number_of_victories = 1 where team_name = 'Saint Marys CA'      and year = 2017;
update tournament_participant set number_of_victories = 1 where team_name = 'Villanova'           and year = 2017;
update tournament_participant set number_of_victories = 1 where team_name = 'Virginia'            and year = 2017;
update tournament_participant set number_of_victories = 1 where team_name = 'Michigan St'         and year = 2017;
update tournament_participant set number_of_victories = 1 where team_name = 'Cincinnati'          and year = 2017;
update tournament_participant set number_of_victories = 1 where team_name = 'Arkansas'            and year = 2017;
update tournament_participant set number_of_victories = 6 where team_name = 'Villanova'           and year = 2018;
update tournament_participant set number_of_victories = 5 where team_name = 'Michigan'            and year = 2018;
update tournament_participant set number_of_victories = 4 where team_name = 'Kansas'              and year = 2018;
update tournament_participant set number_of_victories = 4 where team_name = 'Loyola Chicago'      and year = 2018;
update tournament_participant set number_of_victories = 3 where team_name = 'Duke'                and year = 2018;
update tournament_participant set number_of_victories = 3 where team_name = 'Kansas St'           and year = 2018;
update tournament_participant set number_of_victories = 3 where team_name = 'Texas Tech'          and year = 2018;
update tournament_participant set number_of_victories = 3 where team_name = 'Florida St'          and year = 2018;
update tournament_participant set number_of_victories = 2 where team_name = 'Syracuse'            and year = 2018;
update tournament_participant set number_of_victories = 2 where team_name = 'Purdue'              and year = 2018;
update tournament_participant set number_of_victories = 2 where team_name = 'Texas AM'            and year = 2018;
update tournament_participant set number_of_victories = 2 where team_name = 'Gonzaga'             and year = 2018;
update tournament_participant set number_of_victories = 2 where team_name = 'Clemson'             and year = 2018;
update tournament_participant set number_of_victories = 2 where team_name = 'Nevada'              and year = 2018;
update tournament_participant set number_of_victories = 2 where team_name = 'Kentucky'            and year = 2018;
update tournament_participant set number_of_victories = 2 where team_name = 'West Virginia'       and year = 2018;
update tournament_participant set number_of_victories = 1 where team_name = 'UMBC'                and year = 2018;
update tournament_participant set number_of_victories = 1 where team_name = 'Marshall'            and year = 2018;
update tournament_participant set number_of_victories = 1 where team_name = 'Butler'              and year = 2018;
update tournament_participant set number_of_victories = 1 where team_name = 'Auburn'              and year = 2018;
update tournament_participant set number_of_victories = 1 where team_name = 'Tennessee'           and year = 2018;
update tournament_participant set number_of_victories = 1 where team_name = 'Florida'             and year = 2018;
update tournament_participant set number_of_victories = 1 where team_name = 'Michigan St'         and year = 2018;
update tournament_participant set number_of_victories = 1 where team_name = 'Rhode Island'        and year = 2018;
update tournament_participant set number_of_victories = 1 where team_name = 'Seton Hall'          and year = 2018;
update tournament_participant set number_of_victories = 1 where team_name = 'Houston'             and year = 2018;
update tournament_participant set number_of_victories = 1 where team_name = 'Buffalo'             and year = 2018;
update tournament_participant set number_of_victories = 1 where team_name = 'Cincinnati'          and year = 2018;
update tournament_participant set number_of_victories = 1 where team_name = 'Ohio St'             and year = 2018;
update tournament_participant set number_of_victories = 1 where team_name = 'Alabama'             and year = 2018;
update tournament_participant set number_of_victories = 1 where team_name = 'Xavier'              and year = 2018;
update tournament_participant set number_of_victories = 1 where team_name = 'North Carolina'      and year = 2018;
