package com.makotojava.ncaabb.dl4j.menus;

public enum DataElementMenuChoice {
  // Offense
  AVERAGE_POINTS_PER_GAME(0),
  SCORING_MARGIN_PER_GAME(1),
  NUMBER_FIELD_GOAL_ATTEMPTS_PER_GAME(2),
  FIELD_GOAL_PERCENTAGE(3),
  NUMBER_THREE_POINTERS_PER_GAME(4),
  NUMBER_THREE_POINT_ATTEMPTS_PER_GAME(5),
  THREE_POINT_PERCENTAGE(6),
  NUMBER_FREE_THROW_ATTEMPTS_PER_GAME(7),
  FREE_THROW_PERCENTAGE(8),
  REBOUND_MARGIN(9),
  ASSISTS_PER_GAME(10),
  ASSIST_TO_TURNOVER_RATIO(11),
  // Defense
  AVERAGE_OPPONENT_POINTS_PER_GAME(12),
  NUMBER_OPPONENT_FIELD_GOAL_ATTEMPTS_PER_GAME(13),
  OPPONENT_FIELD_GOAL_PERCENTAGE(14),
  NUMBER_OPPONENT_THREE_POINT_ATTEMPTS_PER_GAME(15),
  OPPONENT_THREE_POINT_PERCENTAGE(16),
  BLOCKS_PER_GAME(17),
  STEALS_PER_GAME(18),
  OPPONENT_TURNOVERS_PER_GAME(19),
  // Errors
  TURNOVERS_PER_GAME(20),
  FOULS_PER_GAME(21),
  NUMBER_DISQUALIFICATIONS(22);

  private int elementIndex;

  DataElementMenuChoice(final int elementIndex) {
    this.elementIndex = elementIndex;
  }

  public int getElementIndex() {
    return elementIndex;
  }
}
